### ISSUE TITLE
main.py terminated with a single warning: Character list from page 4 is empty

### ISSUE THREAD

**Issue by ThomasMHCheng** [sakan811/Honkai-Star-Rail-Characters-Damage-Simulation#25]
2024-11-04 21:34:13.555 | WARNING  | hsrws.hsr_scraper:scrape_hsr_data:84 - Character list from page 4 is empty. Stop web-scraping process

**Comment by sakan811** [comment]
Hi, this is intended as I use while loop to fetch each page. Did you get all the character data? Also, I think you issued on the wrong repo, it should be this one https://github.com/sakan811/Honkai-Star-Rail-A-Few-Fun-Insights-with-Data-Analysis

**Comment by sakan811** [comment]
I will change the logging to prevent a future confusion

**Comment by ThomasMHCheng** [comment]
Sorry for posting on the wrong project, thank you.

**Comment by sakan811** [comment]
I updated the logging. It will no longer show warning log after finishing scraping.
